apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "http-cache.fullname" . }}
  labels:
    {{- include "http-cache.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "http-cache.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "http-cache.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
{{ if .Values.upstream.url }}
            - name: UPSTREAM_URL
              value: {{ .Values.upstream.url | quote }}
{{ end }}
            - name: CACHE_URL
              value: {{ .Values.cache.url | required "cache.url is required" | quote }}
            - name: RUST_LOG
              value: {{ .Values.log.level | quote }}
            - name: LOG_FORMAT
              value: {{ .Values.log.format | quote }}

{{ if .Values.gcs.serviceAccountKey }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/http-cache/gcs/service-account-key.json
{{ end }}
{{ if .Values.env }}
{{ .Values.env | toYaml | indent 12 }}
{{ end }}

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
{{ if .Values.livenessProbe }}
          livenessProbe: {{ .Values.livenessProbe | toYaml | nindent 12 }}
{{ end }}
{{ if .Values.readinessProbe }}
          readinessProbe: {{ .Values.readinessProbe | toYaml | nindent 12 }}
{{ end }}
          volumeMounts:
{{ if .Values.gcs.serviceAccountKey }}
            - name: gcs
              mountPath: /etc/http-cache/gcs
{{ end }}
{{ if .Values.volumeMounts }}
{{ .Values.volumeMounts | toYaml | indent 12 }}
{{ end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
{{ if .Values.gcs.serviceAccountKey }}
        - name: gcs
          secret:
            secretName: {{ include "http-cache.fullname" . }}-gcs
{{ end }}
{{ if .Values.volumes }}
{{ .Values.volumes | toYaml | indent 8 }}
{{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
