{{ if .Values.gcs.serviceAccountKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "http-cache.fullname" . }}-gcs
data:
  service-account-key.json: {{ .Values.gcs.serviceAccountKey | b64enc | quote }}
{{ end }}