#!/usr/bin/env bash

set -e

SCRIPT_DIR="$(dirname "$(realpath "$0")")"
cd "$SCRIPT_DIR/.."

npm run version:bump:recommended
npm run changelog

BASE_VERSION=$(./scripts/version-base)

git commit -a -m "chore(release): $BASE_VERSION"
