name: Helm

on:
  push:
    branches: ["main"]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_REPO: ${{ github.repository }}/helm

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build chart
        run: |
          chart_path="$(realpath charts/http-cache)"
          cd "$(mktemp -d)"
          helm package "$chart_path"
          echo "$GITHUB_TOKEN" | helm registry login -u "GitHubActions" --password-stdin "$REGISTRY"
          helm push $REGISTRY/$IMAGE_NAME:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
