name: Helm

on:
  push:
    branches: ["main"]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_REPO: ${{ github.repository }}/helm

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install node dependencies
        run: npm install

      - id: version
        name: Determine version
        run: |
          version="$(./scripts/version)"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Build chart
        run: |
          chart_path="charts/http-cache"
          dest_dir="$(mktemp -d)"
          push_target="oci://$REGISTRY/$IMAGE_REPO"
          version="$VERSION"

          echo "Authenticating"
          echo "$GITHUB_TOKEN" | helm registry login -u "GitHubActions" --password-stdin "$REGISTRY"

          echo "Building"
          helm package "$chart_path" \
            --destination "$dest_dir" \
            --version "$version" \
            --app-version "$version"

          echo "Pushing to $push_target"
          helm push "$dest_dir/http-cache-$version.tgz" "$push_target"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.version.outputs.version }}
